### ISSUE TITLE
Selecting Clients Page

### ISSUE THREAD

**Issue by noahpc** [pccsei/adit#18]
DUE: Saturday, February the 1st

The requirements:
- Go to page that lists all the clients. (These are technically tickets in our program)
- When the student selects a client, the ticket is assigned to them and a receipt is
  created. Look at the database schema to see details on how the columns will relate.
- Use JavaScript or Ajax to refresh the page constantly to handle multiple requests.
- You will probably need to "hide" the selected clients from the students immediately using JavaScript and then do the database save of those clients in the back-end.

**Comment by asian-invasion** [comment]
I now have the page displaying the clients via tickets (Client will not display if a ticket does not exist for it).

**Comment by noahpc** [comment]
Hey James, please make like a checklist of things that need to work on this page and post it here connected to this issue. Your assignment is to make this page completely functional and ready to be put into action. The sooner this is done, the better. Do as much as you can over break and be prepared to give us all an update when we get back.

**Comment by asian-invasion** [comment]
Code performing AJAX polling needs to be migrated from the clients page to the tickets page since this the client page is not the page that people will be grabbing from.

**Comment by asian-invasion** [comment]
Task completed on 2/1/14
