### ISSUE TITLE
Manage Section Page

### ISSUE THREAD

**Issue by noahpc** [pccsei/adit#19]
By Monday night, 

   The following page should be functional. The manage section page.
- A list of students with their contact and school information with checkboxes next to each name.
- A submit button named "Save Changes"
- A drop-down box that displays teacher actions such as promote student, delete/disable student, add to team.
- A second drop-down box that is displayed when the add to team dropdown is selected, this will probably need something like ajax to make the drop-down work. It will contain the names of all the student managers.

**Comment by James-Mulvihill** [comment]
These are finished. The page isn't completely bug proof nor the most efficient, but it works for the most part.
