### ISSUE TITLE
Overall Design

### ISSUE THREAD

**Issue by noahpc** [pccsei/adit#23]
Implement the overall design of the project in the global style files.

This should include things like what we want tables to look like, the header and footer of the program, etc. 

Once this is completed, you will be assigned different pages to specifically work on. Your first pages will be the selecting clients page that miyashita is working on, the project options page, and the manage section page. 

The more that can be done the better so tackle what you can over break, especially the overall design part.

**Comment by Zachdavid54** [comment]
This Is pretty much done. All that is left is design of the individual pages.
