### ISSUE TITLE
Testing Plan

### ISSUE THREAD

**Issue by noahpc** [pccsei/adit#24]
DUE: Saturday, February the 1st
- Create a document that describes our plan for testing.
  - Include a checklist of things that need to be tested. Be specific.
  - Include date(s) for Software Engineering Class to come and test our product.
  - include date(s) for when the other team will test our product.
  - Specify how we will test. What will be manual? What will be automatic? Will we test the program every day? Twice a week? Once a week?

**Comment by canipejak** [comment]
I made a Word document explaining our testing plan for our project.  I will put it on csmain under development\resources\whitecollar.
