### ISSUE TITLE
Reports pages for the Teacher

### ISSUE THREAD

**Issue by noahpc** [pccsei/adit#29]
Due: Saturday, February 8th

James and Noah will be working on this issue together.

Create the reports pages
      - Sales Report
      - Activities Log
      - Team Summary Page
      - Student Summary Page

All these reports will be based off of selected sections in a drop-down box. This will require that we be sharing information, perhaps using the session token between these pages.

**Comment by James-Mulvihill** [comment]
Everything as far as I can tell is done here, expect for making the total's row always appear at the bottom.
