### ISSUE TITLE
Edit My Client

### ISSUE THREAD

**Issue by canipejak** [pccsei/adit#41]
In the my receipts page, it shows the correct client info at the top of the page with the partial.  However, when you click edit, it will show a different client.  From looking at the database and everything, it is grabbing ticket id and using the corresponding client id with that ticket to show for the edit.  I cannot find how this is happening since the edit is using the same client passed for the show.

**Comment by canipejak** [comment]
Sorry for the close and open a lot, but for some reason I cannot label this as a bug.....but it is a BUG!

**Comment by noahpc** [comment]
JAKE, is this closed?
