### ISSUE TITLE
get_section_number BUG

### ISSUE THREAD

**Issue by asian-invasion** [pccsei/adit#44]
There is a problem with the User.get_section_number method which is causing reports/Activities and reports/sales to fail

**Comment by noahpc** [comment]
What was the scenario when this broke? I am having trouble causing it to fail.
I believe this might have been caused by manipulating receipts so that some receipts do not have the
correct user or don't have a user at all, which would cause this function to fail.

**Comment by asian-invasion** [comment]
data integrity seems to be the problem. will close for now
